In [61]:
import pickle
import numpy as np

In [62]:
Sex = pickle.load(open('Sex.pkl','rb'))
Embarked = pickle.load(open('Embarked.pkl','rb'))
clf = pickle.load(open('Model.pkl','rb'))

In [63]:
# creating a new input 
test_input = np.array([[2,'male',31.0,0,0,105,'S']])

In [64]:
test_input_sex = test_input[:,1].reshape(1,1)

In [65]:
test_input_sex = Sex.transform(test_input_sex)

C:\Users\singl\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [66]:
test_input_sex

array([[1.]])

In [67]:
test_input_embarked = Embarked.transform(test_input[:,-1].reshape(1,1))

In [68]:
test_input_embarked

array([[0., 1.]])

In [69]:
test_input_age = test_input[:,2].reshape(1,1)

In [70]:
test_input_age

array([['31.0']], dtype='<U32')

In [71]:
test_input_new = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_embarked,test_input_sex),axis = 1)

In [74]:
test_input_new

array([['2', '0', '0', '105', '31.0', '0.0', '1.0', '1.0']], dtype='<U32')

In [75]:
# Now we will predict the Sutvived 
clf.predict(test_input_new)

array([0])

In [ ]:
# he is telling that he will not survive