In [89]:
# importing libraries 
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier

In [90]:
# importing the titanic dataset 
df = pd.read_csv(r"C:\Skills\Machine Learning\ML main\Understanding Data\Titanic-Dataset.csv")

In [91]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [92]:
# taking only columns that we will use for our model 
df = df.drop(columns=['PassengerId','Name','Ticket','Cabin'])

In [93]:
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,0,3,male,22.0,1,0,7.2500,S
1,1,1,female,38.0,1,0,71.2833,C
2,1,3,female,26.0,0,0,7.9250,S
3,1,1,female,35.0,1,0,53.1000,S
4,0,3,male,35.0,0,0,8.0500,S


In [94]:
# Step 1 train test split 
x_train, x_test , y_train, y_test = train_test_split(df.iloc[:,1:],df['Survived'],test_size=0.2,random_state=42)

In [95]:
x_train.head()

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
331,1,male,45.5,0,0,28.5000,S
733,2,male,23.0,0,0,13.0000,S
382,3,male,32.0,0,0,7.9250,S
704,3,male,26.0,1,0,7.8542,S
813,3,female,6.0,4,2,31.2750,S


In [96]:
# firstly we will apply simple imputer to handle missing values 
si_age = SimpleImputer()
si_embarked = SimpleImputer(strategy='most_frequent')

In [97]:
x_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
331,1,male,45.5,0,0,28.5000,S
733,2,male,23.0,0,0,13.0000,S
382,3,male,32.0,0,0,7.9250,S
704,3,male,26.0,1,0,7.8542,S
813,3,female,6.0,4,2,31.2750,S
...,...,...,...,...,...,...,...
106,3,female,21.0,0,0,7.6500,S
270,1,male,NaN,0,0,31.0000,S
860,3,male,41.0,2,0,14.1083,S
435,1,female,14.0,1,2,120.0000,S


In [98]:
x_train_age = si_age.fit_transform(x_train[['Age']])
x_train_embarked = si_embarked.fit_transform(x_train[['Embarked']])

x_test_age = si_age.transform(x_test[['Age']])
x_test_embarked = si_embarked.transform(x_test[['Embarked']])

In [99]:
# doing one hot encoding on categorical data
ohe_sex = OneHotEncoder(drop='first',sparse_output=False)
ohe_embarked = OneHotEncoder(drop='first',sparse_output=False)

x_train_sex = ohe_sex.fit_transform(x_train[['Sex']])
x_train_embarked = ohe_embarked.fit_transform(x_train_embarked)

x_test_sex = ohe_sex.transform(x_test[['Sex']])
x_test_embarked = ohe_embarked.transform(x_test_embarked)


In [100]:
x_test_rem

array([[  3.    ,   1.    ,   1.    ,  15.2458],
       [  2.    ,   0.    ,   0.    ,  10.5   ],
       [  3.    ,   0.    ,   0.    ,   7.925 ],
       [  2.    ,   0.    ,   1.    ,  33.    ],
       [  3.    ,   1.    ,   0.    ,  11.2417],
       [  1.    ,   0.    ,   0.    ,  78.85  ],
       [  3.    ,   0.    ,   0.    ,   7.75  ],
       [  3.    ,   2.    ,   0.    ,  18.    ],
       [  3.    ,   0.    ,   0.    ,   7.75  ],
       [  1.    ,   0.    ,   2.    ,  26.2833],
       [  1.    ,   1.    ,   0.    ,  53.1   ],
       [  3.    ,   0.    ,   0.    ,   8.05  ],
       [  3.    ,   3.    ,   1.    ,  25.4667],
       [  3.    ,   0.    ,   0.    ,   7.225 ],
       [  2.    ,   0.    ,   0.    ,  13.    ],
       [  1.    ,   0.    ,   1.    ,  39.4   ],
       [  1.    ,   1.    ,   0.    ,  52.5542],
       [  3.    ,   0.    ,   0.    ,   7.8292],
       [  2.    ,   0.    ,   0.    ,  13.    ],
       [  1.    ,   0.    ,   0.    ,  52.    ],
       [  3.    ,   

In [101]:
x_train_rem

array([[  1.    ,   0.    ,   0.    ,  28.5   ],
       [  2.    ,   0.    ,   0.    ,  13.    ],
       [  3.    ,   0.    ,   0.    ,   7.925 ],
       ...,
       [  3.    ,   2.    ,   0.    ,  14.1083],
       [  1.    ,   1.    ,   2.    , 120.    ],
       [  1.    ,   0.    ,   1.    ,  77.2875]], shape=(712, 4))

In [102]:
x_train_new = np.concatenate((x_train_rem,x_train_age,x_train_embarked,x_train_sex),axis = 1)

In [103]:
x_train_new.shape

(712, 8)

In [104]:
x_test_new = np.concatenate((x_test_rem,x_test_age,x_test_embarked,x_test_sex),axis=1)

In [105]:
x_test_new.shape

(179, 8)

In [106]:
# we combined all the important arrays 
# now we will train our model and predict the values from them
clf = DecisionTreeClassifier()
clf.fit(x_train_new,y_train)

,criterion,'gini'
,splitter,'best'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,None
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


In [107]:
predicted = clf.predict(x_test_new)

In [108]:
predicted 

array([0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1])

In [109]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,predicted)

0.7877094972067039

In [110]:
# we have created a model which has accuracy of 78.77 percentage 
# pickling the model 
import pickle

pickle.dump(ohe_embarked,open('Embarked.pkl','wb'))
pickle.dump(ohe_sex,open('Sex.pkl','wb'))
pickle.dump(clf,open('Model.pkl','wb'))