In [2]:
import numpy as np
#0D tensor/scaler
arr1 = np.array(5) #creating a 0-D tensor which has no dimension and only store a single element
arr1

array(5)

In [4]:
#we can check the dimension of the array we created
arr1.ndim

0

In [7]:
#creating a 1D tensor also known as vector
arr2 = np.array([1,2,3,4,5,6,7,8])
arr2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
arr2.ndim

1

In [13]:
#creating a 2D tensor also known as matrix
arr3 = np.arange(0,16).reshape(4,4)
print(arr3)
print("Dimesion is = ",arr3.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Dimesion is =  2


In [14]:
#creating a nd array of dimension 4
np.arange(0,16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [ ]:
# this all was to understand how the tensors works