In [3]:
#creating numpy/N-D arrays
import numpy as np

In [8]:
arr1 = np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [9]:
 # to check the type of our arr1
type(arr1)

numpy.ndarray

In [11]:
# printing a 2d array
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
# creating array with all elements as zero 
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
# creating array with all elements as one
arr4 = np.ones((2,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
# creating identity martix 
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
#creating array from 0 to a number
arr6 = np.arange(15)
print(arr6)
#creating from a differnt stating number 
arr7 = np.arange(5,11)
print(arr7)
# we can also tell how much gaps should be between them
arr8 = np.arange(10,21,2)
print(arr8)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 5  6  7  8  9 10]
[10 12 14 16 18 20]


In [36]:
#creating array with equidistant points in them
arr9 = np.linspace(0,20,9)
arr9

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. ])

In [37]:
# copying an array
arr10 = np.copy(arr9)
arr10

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. ])