In [3]:
import numpy as np

In [18]:
arr1 = np.random.randint(0,50,(3,3))
arr2 = np.random.randint(0,50,(1,3))
print(arr1)
print(arr2)

[[41 47 45]
 [ 5 16 41]
 [40 18  1]]
[[ 7 44 21]]


In [19]:
# we can see here that we can apply arithmetic operations on diferent shape of arrays also 
print(arr2/arr1)
print(arr2*arr1)
print(arr2+arr1)
print(arr2-arr1)

[[ 0.17073171  0.93617021  0.46666667]
 [ 1.4         2.75        0.51219512]
 [ 0.175       2.44444444 21.        ]]
[[ 287 2068  945]
 [  35  704  861]
 [ 280  792   21]]
[[48 91 66]
 [12 60 62]
 [47 62 22]]
[[-34  -3 -24]
 [  2  28 -20]
 [-33  26  20]]


In [6]:
# now we will check different combinations that we can do in a brodcasting
arr1 = np.arange(1,2).reshape(1,1)
arr2 = np.arange(100,200).reshape(5,20)
# if the array has 1 by 1 dimension then it can be brodcasted with any array
arr1*arr2

array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
        133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
        153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172,
        173, 174, 175, 176, 177, 178, 179],
       [180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192,
        193, 194, 195, 196, 197, 198, 199]])

In [8]:
arr1 = np.arange(0,5).reshape(5,1)
arr2 = np.arange(5,10).reshape(1,5)
arr1*arr2

array([[ 0,  0,  0,  0,  0],
       [ 5,  6,  7,  8,  9],
       [10, 12, 14, 16, 18],
       [15, 18, 21, 24, 27],
       [20, 24, 28, 32, 36]])

we just have to visualize that the arrays can be brodcasted or not just simple as that