In [1]:
import numpy as np

In [7]:
# using random function
arr1 = np.random.random()
arr1

0.9951624190265558

In [11]:
# this gives the same random number again and again
np.random.seed(1)
arr1 = np.random.random()
arr1

0.417022004702574

In [15]:
# to create random float numbers within a range
arr1 = np.random.uniform(1,11,10).reshape(5,2)  #we can also reshape array
arr1

array([[ 5.17304802,  6.58689828],
       [ 2.40386939,  2.98101489],
       [ 9.00744569, 10.68261576],
       [ 4.13424178,  7.92322616],
       [ 9.76389152,  9.94606664]])

In [17]:
# to generate integer values we can use this
arr1 = np.random.randint(0,100,30).reshape(6,5)
arr1

array([[ 8, 88, 13, 47, 72],
       [30, 71,  3, 70, 21],
       [49, 57,  3, 68, 24],
       [43, 76, 26, 52, 80],
       [41, 82, 15, 64, 68],
       [25, 98, 87,  7, 26]], dtype=int32)

In [18]:
#  to get index of max or min values 
print(np.argmax(arr1))
print(np.argmin(arr1))

26
7


In [20]:
#  we can check also if that is correct by indexing 
arr1 = np.ravel(arr1)
arr1[np.argmax(arr1)]

np.int32(98)

In [22]:
# we can chenge values as we need also 
arr1[arr1%2==0]= 3
arr1

array([ 3,  3, 13, 47,  3,  3, 71,  3,  3, 21, 49, 57,  3,  3,  3, 43,  3,
        3,  3,  3, 41,  3, 15,  3,  3, 25,  3, 87,  7,  3], dtype=int32)

In [24]:
# if we want to change elemewnts as we need but dont want to change original array
arr1 = np.random.randint(0,100,30).reshape(6,5)
print(np.where(arr1%2==0,1,-1))
print(arr1)

[[ 1 -1  1  1 -1]
 [ 1  1  1 -1 -1]
 [-1 -1 -1  1 -1]
 [ 1 -1  1  1  1]
 [-1 -1  1 -1  1]
 [ 1 -1  1 -1 -1]]
[[ 0 77  6 52 85]
 [70  2 76 91 21]
 [75  7 77 72 75]
 [76 43 20 30 36]
 [ 7 45 68 57 82]
 [96 13 10 23 81]]


In [27]:
# we can sort the array elements also 
arr1 = np.ravel(arr1)
arr1 = np.sort(arr1)

array([ 0,  2,  6,  7,  7, 10, 13, 20, 21, 23, 30, 36, 43, 45, 52, 57, 68,
       70, 72, 75, 75, 76, 76, 77, 77, 81, 82, 85, 91, 96], dtype=int32)

In [28]:
# we can use the percentile funtion also to get the value as we need
np.percentile(arr1,29.45)

np.float64(22.081)

In [ ]:
#thanks