In [1]:
import numpy as np

In [9]:
arr1 = np.arange(20).reshape(5,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [13]:
# we can select andy input from it by giving its index
arr1[3]

array([12, 13, 14, 15])

In [19]:
# we can select a range also between them
arr1[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
#we can also selct the items inside the item we selected 
arr1[2,2]

np.int64(10)

In [23]:
# to extract collumns till i want
arr1[:4,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [24]:
#extracting 9,10,13,14 from that array
arr1[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [26]:
for i in arr1:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]


In [29]:
for i in np.nditer(arr1):
    print (i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
