In [1]:
import numpy as np

In [9]:
# we used randint to create a 
arr1 = np.random.randint(1,100,(6,5))
arr1

array([[99,  4, 66, 62, 99],
       [60, 63,  4, 96, 57],
       [ 2, 22, 64, 71, 40],
       [99, 53,  3, 42, 80],
       [38, 57, 29, 61, 52],
       [ 7, 96, 16, 97, 98]], dtype=int32)

In [11]:
# this will create a boolean array
(arr1>50)

array([[ True, False,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [False, False,  True,  True, False],
       [ True,  True, False, False,  True],
       [False,  True, False,  True,  True],
       [False,  True, False,  True,  True]])

In [12]:
# to get the elements that are greater than 50 we use
arr1[arr1>50]

array([99, 66, 62, 99, 60, 63, 96, 57, 64, 71, 99, 53, 80, 57, 61, 52, 96,
       97, 98], dtype=int32)

In [18]:
# we can do multiple thing using this 
print(arr1[arr1%10==0])
print(arr1[(arr1>=25) & (arr1%2==0)])

[60 40 80]
[66 62 60 96 64 40 42 80 38 52 96 98]


In [19]:
# we can use it to change values of that numbers also 
arr1[(arr1>=25) & (arr1%2==0)]=0
arr1

array([[99,  4,  0,  0, 99],
       [ 0, 63,  4,  0, 57],
       [ 2, 22,  0, 71,  0],
       [99, 53,  3,  0,  0],
       [ 0, 57, 29, 61,  0],
       [ 7,  0, 16, 97,  0]], dtype=int32)