In [1]:
import numpy as np

In [6]:
# defining 2 nd arrays
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])

In [11]:
# element wise operations
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1+arr2)

[-3 -3 -3 -3 -3 -3]
[ 4 10 18 28 40 54]
[0.25       0.4        0.5        0.57142857 0.625      0.66666667]
[ 5  7  9 11 13 15]


In [13]:
# we can perform operations on single array also 
print(arr1*2)
print(arr1+1)

[ 2  4  6  8 10 12]
[2 3 4 5 6 7]


In [14]:
# checks condition for every element 
arr1>3

array([False, False, False,  True,  True,  True])

In [15]:
# we can also do the dot product of 2 array
arr3=np.arange(0,10).reshape(5,2)
arr4=np.arange(10,20).reshape(2,5)
arr3.dot(arr4)

array([[ 15,  16,  17,  18,  19],
       [ 65,  70,  75,  80,  85],
       [115, 124, 133, 142, 151],
       [165, 178, 191, 204, 217],
       [215, 232, 249, 266, 283]])

In [18]:
# to find maximum or minimum element
print(arr4.max())
print(arr4.min())

19
10


In [25]:
# to print collumn and row, max and min elements
arr4.max(axis = 0)#collumn max
arr4.max(axis = 1)#row max

array([14, 19])

In [26]:
# to find sum of all elements
arr1.sum()

np.int64(21)

In [28]:
#to find sum of elements in all collumn or row
print(arr4.sum(axis=0))#collumn
print(arr4.sum(axis=1))#row

[25 27 29 31 33]
[60 85]


In [29]:
# to find mean of a array
arr4.mean()

np.float64(14.5)

In [33]:
# to calculate standard deviation
arr4.std()

np.float64(2.8722813232690143)

In [ ]:
# there are lots and many operations that we can apply on our arrays we will not cover all because they will come slowly as we implement them on machine learning 
