In [1]:
import numpy as np

In [8]:
arr1 = np.arange(10).reshape(2,5)
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
# ravel funtion can make any array into 1d
arr1.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# reshape we already know

In [9]:
# we can find transpose of array
arr1.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [15]:
# we can combine two arrays of same shape 
arr2 = np.arange(10,20).reshape(2,5)
print(np.hstack((arr1,arr2)))
print(np.vstack((arr1,arr2)))

[[ 0  1  2  3  4 10 11 12 13 14]
 [ 5  6  7  8  9 15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [18]:
# we can split also 
print(np.vsplit(arr1,2))
print(np.hsplit(arr1,5))

[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]
[array([[0],
       [5]]), array([[1],
       [6]]), array([[2],
       [7]]), array([[3],
       [8]]), array([[4],
       [9]])]
